{
  "openapi": "3.0.0",
  "info": {
    "title": "ICA API",
    "description": "IERSE-UNIVERSIDAD DEL AZUAY",
    "license": {
      "name": "MIT License",
      "url": "https://opensource.org/licenses/MIT"
    },
    "version": "0.1.0"
  },
  "paths": {
    "/estacion/{estacionId}": {
      "get": {
        "tags": [
          "Estacion"
        ],
        "summary": "Returns a estacion based on a single ID",
        "description": "Returns the estacion identified by `estacionId`.",
        "operationId": "ica_get_estacion_id",
        "parameters": [
          {
            "$ref": "#/components/parameters/estacionId"
          }
        ],
        "responses": {
          "200": {
            "description": "Estacion",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Estacion"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Estacion"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/Estacion"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      }
    },
    "/phenoff/{phenOffId}": {
      "get": {
        "tags": [
          "PhenOff"
        ],
        "summary": "Returns a phenoff based on a single ID",
        "description": "Returns the phenoff identified by `phenOffId`.",
        "operationId": "ica_get_phenoff_id",
        "parameters": [
          {
            "$ref": "#/components/parameters/phenOffId"
          }
        ],
        "responses": {
          "200": {
            "description": "PhenOff",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PhenOff"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/PhenOff"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/PhenOff"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      }
    },
    "/phenoff/weightPolar/{phenOffId}": {
      "get": {
        "tags": [
          "PhenOff"
        ],
        "summary": "Returns a phenoff based on a single ID",
        "description": "Returns the phenoff identified by `phenOffId`.",
        "operationId": "ica_get_phenoff_weightPolar_id",
        "parameters": [
          {
            "$ref": "#/components/parameters/phenOffId"
          }
        ],
        "responses": {
          "200": {
            "description": "PhenOff",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PhenOff"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/PhenOff"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/PhenOff"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      }
    },
    "/parametros/search/contaminante": {
      "post": {
        "tags": [
          "Parametros"
        ],
        "summary": "Search advance parameters",
        "description": "Search advance parameters",
        "operationId": "ica_search_contaminante_parametros",
        "responses": {
          "200": {
            "description": "Parametros",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Parametros"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Parametros"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/Parametros"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ParametrosSearchData"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/ParametrosSearchData"
              }
            }
          },
          "description": "`Parametros` properties to add to the system",
          "required": true
        }
      }
    },
    "/observations/search": {
      "post": {
        "tags": [
          "Observations"
        ],
        "summary": "Search advance observations",
        "description": "Search advance observations",
        "operationId": "ica_search_observations",
        "responses": {
          "200": {
            "description": "ObservationSearch",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchArray"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchArray"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ObservationsSearchData"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/ObservationsSearchData"
              }
            }
          },
          "description": "`ObservationSearch` properties to add to the system",
          "required": true
        }
      }
    },
    "/observations/search/contaminante": {
      "post": {
        "tags": [
          "Observations"
        ],
        "summary": "Search advance observations",
        "description": "Search advance observations",
        "operationId": "ica_search_observations_contaminante",
        "responses": {
          "200": {
            "description": "ObservationsSearchContaminante",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchContaminanteArray"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchContaminanteArray"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchContaminanteArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ObservationsSearchData"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/ObservationsSearchData"
              }
            }
          },
          "description": "`ObservationsSearchContaminante` properties to add to the system",
          "required": true
        }
      }
    },
    "/observations/stadistic/general": {
      "post": {
        "tags": [
          "Observations"
        ],
        "summary": "Search advance observations",
        "description": "Search advance observations",
        "operationId": "ica_stadictis_general_contaminante",
        "responses": {
          "200": {
            "description": "ObservationsSearchContaminante",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsStadisticsGeneralArray"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsStadisticsGeneralArray"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsStadisticsGeneralArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ObservationsStadisticsGeneralData"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/ObservationsStadisticsGeneralData"
              }
            }
          },
          "description": "`ObservationsSearchContaminante` properties to add to the system",
          "required": true
        }
      }
    },
    "/observations/search/ICA": {
      "post": {
        "tags": [
          "Observations"
        ],
        "summary": "Search advance observations",
        "description": "Search advance ica observations",
        "operationId": "ica_search_ICA_contaminante",
        "responses": {
          "200": {
            "description": "ObservationsSearchICA",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchICAArray"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchICAArray"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/ObservationsSearchICAArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ObservationsSearchICAData"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/ObservationsSearchICAData"
              }
            }
          },
          "description": "`ObservationsSearchICA` properties to add to the system",
          "required": true
        }
      }
    },
    "/observations/maxHour": {
      "get": {
        "tags": [
          "Observations"
        ],
        "summary": "Returns a max hour",
        "description": "Returns the max hour",
        "operationId": "ica_get_max_hour_observation",
        "responses": {
          "200": {
            "description": "MaxHour",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MaxHour"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/MaxHour"
                }
              },
              "application/x-yaml": {
                "schema": {
                  "$ref": "#/components/schemas/MaxHour"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Estacion",
      "description": "Estacion management"
    },
    {
      "name": "PhenOff",
      "description": "PhenOff management"
    },
    {
      "name": "Parametros",
      "description": "Parametros management"
    },
    {
      "name": "Observations",
      "description": "Observations management"
    }
  ],
  "servers": [
    {
      "url": "http://localhost:8000/api/v1"
    }
  ],
  "components": {
    "parameters": {
      "estacionId": {
        "name": "estacionId",
        "in": "path",
        "description": "ID of estacion",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32"
        }
      },
      "phenOffId": {
        "name": "phenOffId",
        "in": "path",
        "description": "ID of phenOff",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    },
    "responses": {
      "403_Forbidden_Response": {
        "description": "`Forbidden` You don't have permission to access",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/xml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/x-yaml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          }
        }
      },
      "404_Resource_Not_Found_Response": {
        "description": "`Not found` resource not found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/xml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/x-yaml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          }
        }
      }
    },
    "schemas": {
      "Estacion": {
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "description": "Estacion Id",
            "type": "integer",
            "format": "int32"
          },
          "estacionnombre": {
            "description": "Estacion nombre",
            "type": "string"
          },
          "ubicacion": {
            "description": "Estacion ubicacion",
            "type": "string"
          }
        },
        "example": {
          "estacion": {
            "id": 1508,
            "estacionnombre": "Estacion nombre",
            "ubicacion": "Estacion ubicacion"
          }
        }
      },
      "PhenOff": {
        "required": [
          "phenomenon_id"
        ],
        "properties": {
          "phenomenon_id": {
            "description": "PhenOff Id",
            "type": "string"
          },
          "unidad": {
            "description": "PhenOff unidad",
            "type": "string"
          },
          "peso_molecular": {
            "description": "PhenOff peso molecular",
            "type": "string"
          },
          "sensor": {
            "description": "PhenOff sensor",
            "type": "string"
          }
        },
        "example": {
          "PhenOff": {
            "phenOffId": 1508,
            "unidad": "PhenOff Id",
            "peso_molecular": "PhenOff unidad",
            "sensor": "PhenOff sensor"
          }
        }
      },
      "Parametros": {
        "properties": {
          "contaminante": {
            "description": "Phenomenon Id",
            "type": "string"
          },
          "valor": {
            "type": "string"
          },
          "rango": {
            "type": "string"
          },
          "color": {
            "type": "string"
          }
        },
        "example": {
          "Parametros": {
            "contaminante": "CO",
            "valor": 21,
            "rango": "BUENO",
            "color": null
          }
        }
      },
      "MaxHour": {
        "properties": {
          "maxHour": {
            "type": "array"
          }
        },
        "example": {
          "observations": {
            "maxHour": "2016-05-17 10:30:00-05"
          }
        }
      },
      "ObservationsSearch": {
        "properties": {
          "timeStamp": {
            "type": "array"
          },
          "phenomenonId": {
            "type": "string"
          },
          "valor": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "ObservationsSearch": {
            "timeStamp": {
              "date": "2018-05-17 10:11:00.000000",
              "timezone_type": 1,
              "timezone": "-05:00"
            },
            "phenomenonId": "urn:ogc:def:phenomenon:OGC:1.0.30:O3",
            "valor": 18.7594803046
          }
        }
      },
      "ObservationsSearchContaminante": {
        "properties": {
          "phenomenonId": {
            "type": "string"
          },
          "timeStamp": {
            "type": "array"
          },
          "valor": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "ObservationsSearchContaminante": {
            "phenomenonId": "O3",
            "timeStamp": {
              "date": "2018-05-17 10:11:00.000000",
              "timezone_type": 1,
              "timezone": "-05:00"
            },
            "valor": 18.76
          }
        }
      },
      "ObservationsStadisticsGeneral": {
        "required": [
          "phenomenonId",
          "maximo",
          "minimo",
          "promedio"
        ],
        "properties": {
          "phenomenonId": {
            "type": "string"
          },
          "maximo": {
            "type": "integer",
            "format": "int32"
          },
          "minimo": {
            "type": "integer",
            "format": "int32"
          },
          "promedio": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "phenomenonId": "urn:ogc:def:phenomenon:OGC:1.0.30:SO2",
          "maximo": 26.6751036532,
          "minimo": 18.5733297548,
          "promedio": 23.31629777748
        }
      },
      "ObservationsSearchICA": {
        "required": [
          "phenomenonId",
          "promedio"
        ],
        "properties": {
          "phenomenonId": {
            "type": "string"
          },
          "promedio": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "phenomenonId": "urn:ogc:def:phenomenon:OGC:1.0.30:SO2",
          "promedio": 23.31629777748
        }
      },
      "ParametrosSearchData": {
        "required": [
          "contaminanteId",
          "valor"
        ],
        "properties": {
          "contaminanteId": {
            "description": "Phenomenon Id",
            "type": "string"
          },
          "valor": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "contaminanteId": "CO",
          "valor": 30
        }
      },
      "ObservationsSearchData": {
        "required": [
          "initial_time_stamp",
          "final_time_stamp",
          "Id"
        ],
        "properties": {
          "initial_time_stamp": {
            "type": "string"
          },
          "final_time_stamp": {
            "type": "string"
          },
          "Id": {
            "type": "string"
          }
        },
        "example": {
          "initial_time_stamp": "2018-05-17 10:11:00-05",
          "final_time_stamp": "2018-05-17 10:50:00-05",
          "Id": "O3"
        }
      },
      "ObservationsStadisticsGeneralData": {
        "required": [
          "initial_time_stamp",
          "final_time_stamp",
          "O3Id",
          "SO2Id",
          "PM2_5Id",
          "COId",
          "NO2Id"
        ],
        "properties": {
          "initial_time_stamp": {
            "type": "string"
          },
          "final_time_stamp": {
            "type": "string"
          },
          "O3Id": {
            "type": "string"
          },
          "SO2Id": {
            "type": "string"
          },
          "PM2_5Id": {
            "type": "string"
          },
          "COId": {
            "type": "string"
          },
          "NO2Id": {
            "type": "string"
          }
        },
        "example": {
          "initial_time_stamp": "2018-05-17 10:11:00-05",
          "final_time_stamp": "2018-05-17 10:50:00-05",
          "O3Id": "O3",
          "SO2Id": "SO2",
          "PM2_5Id": "PM2_5",
          "COId": "CO",
          "NO2Id": "NO2"
        }
      },
      "ObservationsSearchICAData": {
        "required": [
          "initial_time_stamp",
          "final_time_stamp"
        ],
        "properties": {
          "initial_time_stamp": {
            "type": "string"
          },
          "final_time_stamp": {
            "type": "string"
          }
        },
        "example": {
          "initial_time_stamp": "2018-05-17 10:11:00-05",
          "final_time_stamp": "2018-05-17 10:50:00-05"
        }
      },
      "ObservationsSearchArray": {
        "properties": {
          "ObservationsSearch": {
            "description": "Observation array",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ObservationsSearch"
            }
          }
        }
      },
      "ObservationsSearchContaminanteArray": {
        "properties": {
          "ObservationsSearchContaminante": {
            "description": "Observation array",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ObservationsSearchContaminante"
            }
          }
        }
      },
      "ObservationsStadisticsGeneralArray": {
        "properties": {
          "ObservationsStadisticsGeneral": {
            "description": "Observation stadtics array",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ObservationsStadisticsGeneral"
            }
          }
        }
      },
      "ObservationsSearchICAArray": {
        "properties": {
          "ObservationsSearchICA": {
            "description": "Observation stadtics array",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ObservationsSearchICA"
            }
          }
        }
      },
      "Message": {
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "description": "Response code",
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "description": "Response message",
            "type": "string"
          }
        },
        "example": {
          "message": {
            "code": "HTTP code",
            "message": "Response Message"
          }
        }
      }
    }
  }
}